# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - lint
  - build
  - test
  - cherry-pick
  - package
  - smoketest

variables:
  CONTAINER_REGISTRY: docker.xcoresigma.com/docker
  XCORE_LLM_C: ${CI_PROJECT_DIR}/build/Release

  # Branches that has been shipped to customers that need to be long-term maintained
  LTS_BRANCHES: 'release-iie-v1.1.1'

  # Current releasing branches
  RELEASE_BRANCHES: 'br1.2'

  # Branches that will apply cherry-pick job
  CHERRY_PICK_TARGET_BRANCHES: '${RELEASE_BRANCHES} ${LTS_BRANCHES}'

  # The list of branches that will trigger the build image job
  BUILD_IMAGE_BRANCHS: 'main test-ci ${RELEASE_BRANCHES} ${LTS_BRANCHES}'

SmokeTest-aarch64-ascend:
  stage: smoketest
  when: manual
  before_script:
  - mkdir -p ~/.ssh
  - cp "$TESTSERVER_SSH_KEY" ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  variables:
    MODEL_LIST:
      value: "DeepSeek-R1-AWQ,DeepSeek-R1-W8A8,DeepSeek-R1-Distill-Qwen-1.5B"
    ARCH: aarch64-ascend
    # COMMIT_SHORT_SHA: ${CI_COMMIT_SHORT_SHA}
    COMMIT_SHORT_SHA: cf45306e
    IMAGE: ${CONTAINER_REGISTRY}/siginfer-${ARCH}:main-${COMMIT_SHORT_SHA}
  script:
    - echo "Smoke Test starting..."
    - echo "MODEL_LIST = $MODEL_LIST"
    - echo "Version = $IMAGE"
    - |
      ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null s_limingge@192.168.100.106 "
        set -m
        if [ ! -d /home/s_limingge/ci_autotest ]; then
            git clone http://git.xcoresigma.com/xcore-sigma/autotest.git ci_autotest
        else
            cd /home/s_limingge/ci_autotest
            git fetch --all
            git reset --hard origin/main
            git pull origin main
        fi
        cd /home/s_limingge/ci_autotest/ascend_test_suite
        mkdir -p main-${COMMIT_SHORT_SHA}
        sed -i '254s/False/True/' SendMsgToBot.py
        cp latest/SigInfer_model_list.xlsx main-${COMMIT_SHORT_SHA}
        ./deamon.sh \
          Smoke \
          SigInfer \
          '${MODEL_LIST}' \
          main-${COMMIT_SHORT_SHA}
      "
  timeout: 7 hour 30 minutes
  tags:
    - "910_ascend"
  except:
    - test-ci

